//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("tela_p3Model", "FK_tb_prt_Folder_IdFolderParent", "tb_prt_Folder", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Portal.tb_prt_Folder), "tb_prt_Folder1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Portal.tb_prt_Folder), true)]
[assembly: EdmRelationshipAttribute("tela_p3Model", "FK_tb_prt_Page_IdFolder", "tb_prt_Folder", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Portal.tb_prt_Folder), "tb_prt_Page", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Portal.tb_prt_Page), true)]
[assembly: EdmRelationshipAttribute("tela_p3Model", "FK_tb_prt_Page_IdTemplate", "tb_prt_Template", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Portal.tb_prt_Template), "tb_prt_Page", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Portal.tb_prt_Page), true)]

#endregion

namespace Portal
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PortalEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PortalEntities object using the connection string found in the 'PortalEntities' section of the application configuration file.
        /// </summary>
        public PortalEntities() : base("name=PortalEntities", "PortalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PortalEntities object.
        /// </summary>
        public PortalEntities(string connectionString) : base(connectionString, "PortalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PortalEntities object.
        /// </summary>
        public PortalEntities(EntityConnection connection) : base(connection, "PortalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_prt_Control> tb_prt_Control
        {
            get
            {
                if ((_tb_prt_Control == null))
                {
                    _tb_prt_Control = base.CreateObjectSet<tb_prt_Control>("tb_prt_Control");
                }
                return _tb_prt_Control;
            }
        }
        private ObjectSet<tb_prt_Control> _tb_prt_Control;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_prt_Folder> tb_prt_Folder
        {
            get
            {
                if ((_tb_prt_Folder == null))
                {
                    _tb_prt_Folder = base.CreateObjectSet<tb_prt_Folder>("tb_prt_Folder");
                }
                return _tb_prt_Folder;
            }
        }
        private ObjectSet<tb_prt_Folder> _tb_prt_Folder;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_prt_Page> tb_prt_Page
        {
            get
            {
                if ((_tb_prt_Page == null))
                {
                    _tb_prt_Page = base.CreateObjectSet<tb_prt_Page>("tb_prt_Page");
                }
                return _tb_prt_Page;
            }
        }
        private ObjectSet<tb_prt_Page> _tb_prt_Page;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_prt_Template> tb_prt_Template
        {
            get
            {
                if ((_tb_prt_Template == null))
                {
                    _tb_prt_Template = base.CreateObjectSet<tb_prt_Template>("tb_prt_Template");
                }
                return _tb_prt_Template;
            }
        }
        private ObjectSet<tb_prt_Template> _tb_prt_Template;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_prt_UrlMapping> tb_prt_UrlMapping
        {
            get
            {
                if ((_tb_prt_UrlMapping == null))
                {
                    _tb_prt_UrlMapping = base.CreateObjectSet<tb_prt_UrlMapping>("tb_prt_UrlMapping");
                }
                return _tb_prt_UrlMapping;
            }
        }
        private ObjectSet<tb_prt_UrlMapping> _tb_prt_UrlMapping;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_prt_Control EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_prt_Control(tb_prt_Control tb_prt_Control)
        {
            base.AddObject("tb_prt_Control", tb_prt_Control);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_prt_Folder EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_prt_Folder(tb_prt_Folder tb_prt_Folder)
        {
            base.AddObject("tb_prt_Folder", tb_prt_Folder);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_prt_Page EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_prt_Page(tb_prt_Page tb_prt_Page)
        {
            base.AddObject("tb_prt_Page", tb_prt_Page);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_prt_Template EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_prt_Template(tb_prt_Template tb_prt_Template)
        {
            base.AddObject("tb_prt_Template", tb_prt_Template);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_prt_UrlMapping EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_prt_UrlMapping(tb_prt_UrlMapping tb_prt_UrlMapping)
        {
            base.AddObject("tb_prt_UrlMapping", tb_prt_UrlMapping);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="tela_p3Model", Name="tb_prt_Control")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_prt_Control : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_prt_Control object.
        /// </summary>
        /// <param name="idControl">Initial value of the IdControl property.</param>
        /// <param name="idModule">Initial value of the IdModule property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="class">Initial value of the Class property.</param>
        public static tb_prt_Control Createtb_prt_Control(global::System.Int32 idControl, global::System.Int32 idModule, global::System.String name, global::System.String @class)
        {
            tb_prt_Control tb_prt_Control = new tb_prt_Control();
            tb_prt_Control.IdControl = idControl;
            tb_prt_Control.IdModule = idModule;
            tb_prt_Control.Name = name;
            tb_prt_Control.Class = @class;
            return tb_prt_Control;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdControl
        {
            get
            {
                return _IdControl;
            }
            set
            {
                if (_IdControl != value)
                {
                    OnIdControlChanging(value);
                    ReportPropertyChanging("IdControl");
                    _IdControl = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdControl");
                    OnIdControlChanged();
                }
            }
        }
        private global::System.Int32 _IdControl;
        partial void OnIdControlChanging(global::System.Int32 value);
        partial void OnIdControlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdModule
        {
            get
            {
                return _IdModule;
            }
            set
            {
                OnIdModuleChanging(value);
                ReportPropertyChanging("IdModule");
                _IdModule = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdModule");
                OnIdModuleChanged();
            }
        }
        private global::System.Int32 _IdModule;
        partial void OnIdModuleChanging(global::System.Int32 value);
        partial void OnIdModuleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Class
        {
            get
            {
                return _Class;
            }
            set
            {
                OnClassChanging(value);
                ReportPropertyChanging("Class");
                _Class = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Class");
                OnClassChanged();
            }
        }
        private global::System.String _Class;
        partial void OnClassChanging(global::System.String value);
        partial void OnClassChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="tela_p3Model", Name="tb_prt_Folder")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_prt_Folder : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_prt_Folder object.
        /// </summary>
        /// <param name="idFolder">Initial value of the IdFolder property.</param>
        /// <param name="idWebSite">Initial value of the IdWebSite property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static tb_prt_Folder Createtb_prt_Folder(global::System.Int32 idFolder, global::System.Int32 idWebSite, global::System.String name)
        {
            tb_prt_Folder tb_prt_Folder = new tb_prt_Folder();
            tb_prt_Folder.IdFolder = idFolder;
            tb_prt_Folder.IdWebSite = idWebSite;
            tb_prt_Folder.Name = name;
            return tb_prt_Folder;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdFolder
        {
            get
            {
                return _IdFolder;
            }
            set
            {
                if (_IdFolder != value)
                {
                    OnIdFolderChanging(value);
                    ReportPropertyChanging("IdFolder");
                    _IdFolder = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdFolder");
                    OnIdFolderChanged();
                }
            }
        }
        private global::System.Int32 _IdFolder;
        partial void OnIdFolderChanging(global::System.Int32 value);
        partial void OnIdFolderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdWebSite
        {
            get
            {
                return _IdWebSite;
            }
            set
            {
                OnIdWebSiteChanging(value);
                ReportPropertyChanging("IdWebSite");
                _IdWebSite = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdWebSite");
                OnIdWebSiteChanged();
            }
        }
        private global::System.Int32 _IdWebSite;
        partial void OnIdWebSiteChanging(global::System.Int32 value);
        partial void OnIdWebSiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdFolderParent
        {
            get
            {
                return _IdFolderParent;
            }
            set
            {
                OnIdFolderParentChanging(value);
                ReportPropertyChanging("IdFolderParent");
                _IdFolderParent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdFolderParent");
                OnIdFolderParentChanged();
            }
        }
        private Nullable<global::System.Int32> _IdFolderParent;
        partial void OnIdFolderParentChanging(Nullable<global::System.Int32> value);
        partial void OnIdFolderParentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tela_p3Model", "FK_tb_prt_Folder_IdFolderParent", "tb_prt_Folder1")]
        public EntityCollection<tb_prt_Folder> tb_prt_Folder1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_prt_Folder>("tela_p3Model.FK_tb_prt_Folder_IdFolderParent", "tb_prt_Folder1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_prt_Folder>("tela_p3Model.FK_tb_prt_Folder_IdFolderParent", "tb_prt_Folder1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tela_p3Model", "FK_tb_prt_Folder_IdFolderParent", "tb_prt_Folder")]
        public tb_prt_Folder tb_prt_Folder2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_prt_Folder>("tela_p3Model.FK_tb_prt_Folder_IdFolderParent", "tb_prt_Folder").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_prt_Folder>("tela_p3Model.FK_tb_prt_Folder_IdFolderParent", "tb_prt_Folder").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_prt_Folder> tb_prt_Folder2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_prt_Folder>("tela_p3Model.FK_tb_prt_Folder_IdFolderParent", "tb_prt_Folder");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_prt_Folder>("tela_p3Model.FK_tb_prt_Folder_IdFolderParent", "tb_prt_Folder", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tela_p3Model", "FK_tb_prt_Page_IdFolder", "tb_prt_Page")]
        public EntityCollection<tb_prt_Page> tb_prt_Page
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_prt_Page>("tela_p3Model.FK_tb_prt_Page_IdFolder", "tb_prt_Page");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_prt_Page>("tela_p3Model.FK_tb_prt_Page_IdFolder", "tb_prt_Page", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="tela_p3Model", Name="tb_prt_Page")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_prt_Page : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_prt_Page object.
        /// </summary>
        /// <param name="idPage">Initial value of the IdPage property.</param>
        /// <param name="idFolder">Initial value of the IdFolder property.</param>
        /// <param name="idWebSite">Initial value of the IdWebSite property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="url">Initial value of the Url property.</param>
        /// <param name="html">Initial value of the Html property.</param>
        public static tb_prt_Page Createtb_prt_Page(global::System.Int32 idPage, global::System.Int32 idFolder, global::System.Int32 idWebSite, global::System.String name, global::System.String url, global::System.String html)
        {
            tb_prt_Page tb_prt_Page = new tb_prt_Page();
            tb_prt_Page.IdPage = idPage;
            tb_prt_Page.IdFolder = idFolder;
            tb_prt_Page.IdWebSite = idWebSite;
            tb_prt_Page.Name = name;
            tb_prt_Page.Url = url;
            tb_prt_Page.Html = html;
            return tb_prt_Page;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPage
        {
            get
            {
                return _IdPage;
            }
            set
            {
                if (_IdPage != value)
                {
                    OnIdPageChanging(value);
                    ReportPropertyChanging("IdPage");
                    _IdPage = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdPage");
                    OnIdPageChanged();
                }
            }
        }
        private global::System.Int32 _IdPage;
        partial void OnIdPageChanging(global::System.Int32 value);
        partial void OnIdPageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdTemplate
        {
            get
            {
                return _IdTemplate;
            }
            set
            {
                OnIdTemplateChanging(value);
                ReportPropertyChanging("IdTemplate");
                _IdTemplate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdTemplate");
                OnIdTemplateChanged();
            }
        }
        private Nullable<global::System.Int32> _IdTemplate;
        partial void OnIdTemplateChanging(Nullable<global::System.Int32> value);
        partial void OnIdTemplateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdFolder
        {
            get
            {
                return _IdFolder;
            }
            set
            {
                OnIdFolderChanging(value);
                ReportPropertyChanging("IdFolder");
                _IdFolder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdFolder");
                OnIdFolderChanged();
            }
        }
        private global::System.Int32 _IdFolder;
        partial void OnIdFolderChanging(global::System.Int32 value);
        partial void OnIdFolderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdWebSite
        {
            get
            {
                return _IdWebSite;
            }
            set
            {
                OnIdWebSiteChanging(value);
                ReportPropertyChanging("IdWebSite");
                _IdWebSite = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdWebSite");
                OnIdWebSiteChanged();
            }
        }
        private global::System.Int32 _IdWebSite;
        partial void OnIdWebSiteChanging(global::System.Int32 value);
        partial void OnIdWebSiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Html
        {
            get
            {
                return _Html;
            }
            set
            {
                OnHtmlChanging(value);
                ReportPropertyChanging("Html");
                _Html = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Html");
                OnHtmlChanged();
            }
        }
        private global::System.String _Html;
        partial void OnHtmlChanging(global::System.String value);
        partial void OnHtmlChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tela_p3Model", "FK_tb_prt_Page_IdFolder", "tb_prt_Folder")]
        public tb_prt_Folder tb_prt_Folder
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_prt_Folder>("tela_p3Model.FK_tb_prt_Page_IdFolder", "tb_prt_Folder").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_prt_Folder>("tela_p3Model.FK_tb_prt_Page_IdFolder", "tb_prt_Folder").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_prt_Folder> tb_prt_FolderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_prt_Folder>("tela_p3Model.FK_tb_prt_Page_IdFolder", "tb_prt_Folder");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_prt_Folder>("tela_p3Model.FK_tb_prt_Page_IdFolder", "tb_prt_Folder", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tela_p3Model", "FK_tb_prt_Page_IdTemplate", "tb_prt_Template")]
        public tb_prt_Template tb_prt_Template
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_prt_Template>("tela_p3Model.FK_tb_prt_Page_IdTemplate", "tb_prt_Template").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_prt_Template>("tela_p3Model.FK_tb_prt_Page_IdTemplate", "tb_prt_Template").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_prt_Template> tb_prt_TemplateReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_prt_Template>("tela_p3Model.FK_tb_prt_Page_IdTemplate", "tb_prt_Template");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_prt_Template>("tela_p3Model.FK_tb_prt_Page_IdTemplate", "tb_prt_Template", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="tela_p3Model", Name="tb_prt_Template")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_prt_Template : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_prt_Template object.
        /// </summary>
        /// <param name="idTemplate">Initial value of the IdTemplate property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="html">Initial value of the Html property.</param>
        public static tb_prt_Template Createtb_prt_Template(global::System.Int32 idTemplate, global::System.String name, global::System.String html)
        {
            tb_prt_Template tb_prt_Template = new tb_prt_Template();
            tb_prt_Template.IdTemplate = idTemplate;
            tb_prt_Template.Name = name;
            tb_prt_Template.Html = html;
            return tb_prt_Template;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdTemplate
        {
            get
            {
                return _IdTemplate;
            }
            set
            {
                if (_IdTemplate != value)
                {
                    OnIdTemplateChanging(value);
                    ReportPropertyChanging("IdTemplate");
                    _IdTemplate = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdTemplate");
                    OnIdTemplateChanged();
                }
            }
        }
        private global::System.Int32 _IdTemplate;
        partial void OnIdTemplateChanging(global::System.Int32 value);
        partial void OnIdTemplateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Html
        {
            get
            {
                return _Html;
            }
            set
            {
                OnHtmlChanging(value);
                ReportPropertyChanging("Html");
                _Html = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Html");
                OnHtmlChanged();
            }
        }
        private global::System.String _Html;
        partial void OnHtmlChanging(global::System.String value);
        partial void OnHtmlChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("tela_p3Model", "FK_tb_prt_Page_IdTemplate", "tb_prt_Page")]
        public EntityCollection<tb_prt_Page> tb_prt_Page
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_prt_Page>("tela_p3Model.FK_tb_prt_Page_IdTemplate", "tb_prt_Page");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_prt_Page>("tela_p3Model.FK_tb_prt_Page_IdTemplate", "tb_prt_Page", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="tela_p3Model", Name="tb_prt_UrlMapping")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_prt_UrlMapping : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_prt_UrlMapping object.
        /// </summary>
        /// <param name="idWebSite">Initial value of the IdWebSite property.</param>
        /// <param name="urlFrom">Initial value of the UrlFrom property.</param>
        /// <param name="urlTo">Initial value of the UrlTo property.</param>
        public static tb_prt_UrlMapping Createtb_prt_UrlMapping(global::System.Int32 idWebSite, global::System.String urlFrom, global::System.String urlTo)
        {
            tb_prt_UrlMapping tb_prt_UrlMapping = new tb_prt_UrlMapping();
            tb_prt_UrlMapping.IdWebSite = idWebSite;
            tb_prt_UrlMapping.UrlFrom = urlFrom;
            tb_prt_UrlMapping.UrlTo = urlTo;
            return tb_prt_UrlMapping;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdWebSite
        {
            get
            {
                return _IdWebSite;
            }
            set
            {
                if (_IdWebSite != value)
                {
                    OnIdWebSiteChanging(value);
                    ReportPropertyChanging("IdWebSite");
                    _IdWebSite = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdWebSite");
                    OnIdWebSiteChanged();
                }
            }
        }
        private global::System.Int32 _IdWebSite;
        partial void OnIdWebSiteChanging(global::System.Int32 value);
        partial void OnIdWebSiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UrlFrom
        {
            get
            {
                return _UrlFrom;
            }
            set
            {
                if (_UrlFrom != value)
                {
                    OnUrlFromChanging(value);
                    ReportPropertyChanging("UrlFrom");
                    _UrlFrom = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UrlFrom");
                    OnUrlFromChanged();
                }
            }
        }
        private global::System.String _UrlFrom;
        partial void OnUrlFromChanging(global::System.String value);
        partial void OnUrlFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UrlTo
        {
            get
            {
                return _UrlTo;
            }
            set
            {
                OnUrlToChanging(value);
                ReportPropertyChanging("UrlTo");
                _UrlTo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UrlTo");
                OnUrlToChanged();
            }
        }
        private global::System.String _UrlTo;
        partial void OnUrlToChanging(global::System.String value);
        partial void OnUrlToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DtFrom
        {
            get
            {
                return _DtFrom;
            }
            set
            {
                OnDtFromChanging(value);
                ReportPropertyChanging("DtFrom");
                _DtFrom = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DtFrom");
                OnDtFromChanged();
            }
        }
        private Nullable<global::System.DateTime> _DtFrom;
        partial void OnDtFromChanging(Nullable<global::System.DateTime> value);
        partial void OnDtFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DtTo
        {
            get
            {
                return _DtTo;
            }
            set
            {
                OnDtToChanging(value);
                ReportPropertyChanging("DtTo");
                _DtTo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DtTo");
                OnDtToChanged();
            }
        }
        private Nullable<global::System.DateTime> _DtTo;
        partial void OnDtToChanging(Nullable<global::System.DateTime> value);
        partial void OnDtToChanged();

        #endregion
    
    }

    #endregion
    
}
