//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("PortalModel", "FK_porFolder_IdFolderParent", "porFolder", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Portal.porFolder), "porFolder1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Portal.porFolder), true)]
[assembly: EdmRelationshipAttribute("PortalModel", "FK_porPage_IdFolder", "porFolder", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Portal.porFolder), "porPage", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Portal.porPage), true)]
[assembly: EdmRelationshipAttribute("PortalModel", "FK_porPage_IdTemplate", "porTemplate", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Portal.porTemplate), "porPage", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Portal.porPage), true)]

#endregion

namespace Portal
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PortalEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PortalEntities object using the connection string found in the 'PortalEntities' section of the application configuration file.
        /// </summary>
        public PortalEntities() : base("name=PortalEntities", "PortalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PortalEntities object.
        /// </summary>
        public PortalEntities(string connectionString) : base(connectionString, "PortalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PortalEntities object.
        /// </summary>
        public PortalEntities(EntityConnection connection) : base(connection, "PortalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<porControl> porControls
        {
            get
            {
                if ((_porControls == null))
                {
                    _porControls = base.CreateObjectSet<porControl>("porControls");
                }
                return _porControls;
            }
        }
        private ObjectSet<porControl> _porControls;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<porFolder> porFolders
        {
            get
            {
                if ((_porFolders == null))
                {
                    _porFolders = base.CreateObjectSet<porFolder>("porFolders");
                }
                return _porFolders;
            }
        }
        private ObjectSet<porFolder> _porFolders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<porPage> porPages
        {
            get
            {
                if ((_porPages == null))
                {
                    _porPages = base.CreateObjectSet<porPage>("porPages");
                }
                return _porPages;
            }
        }
        private ObjectSet<porPage> _porPages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<porTemplate> porTemplates
        {
            get
            {
                if ((_porTemplates == null))
                {
                    _porTemplates = base.CreateObjectSet<porTemplate>("porTemplates");
                }
                return _porTemplates;
            }
        }
        private ObjectSet<porTemplate> _porTemplates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<porUrlMapping> porUrlMappings
        {
            get
            {
                if ((_porUrlMappings == null))
                {
                    _porUrlMappings = base.CreateObjectSet<porUrlMapping>("porUrlMappings");
                }
                return _porUrlMappings;
            }
        }
        private ObjectSet<porUrlMapping> _porUrlMappings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<porPagePartial> porPagePartials
        {
            get
            {
                if ((_porPagePartials == null))
                {
                    _porPagePartials = base.CreateObjectSet<porPagePartial>("porPagePartials");
                }
                return _porPagePartials;
            }
        }
        private ObjectSet<porPagePartial> _porPagePartials;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the porControls EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToporControls(porControl porControl)
        {
            base.AddObject("porControls", porControl);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the porFolders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToporFolders(porFolder porFolder)
        {
            base.AddObject("porFolders", porFolder);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the porPages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToporPages(porPage porPage)
        {
            base.AddObject("porPages", porPage);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the porTemplates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToporTemplates(porTemplate porTemplate)
        {
            base.AddObject("porTemplates", porTemplate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the porUrlMappings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToporUrlMappings(porUrlMapping porUrlMapping)
        {
            base.AddObject("porUrlMappings", porUrlMapping);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the porPagePartials EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToporPagePartials(porPagePartial porPagePartial)
        {
            base.AddObject("porPagePartials", porPagePartial);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PortalModel", Name="porControl")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class porControl : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new porControl object.
        /// </summary>
        /// <param name="idControl">Initial value of the IdControl property.</param>
        /// <param name="idModule">Initial value of the IdModule property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="route">Initial value of the Route property.</param>
        public static porControl CreateporControl(global::System.Int32 idControl, global::System.Int32 idModule, global::System.String name, global::System.String route)
        {
            porControl porControl = new porControl();
            porControl.IdControl = idControl;
            porControl.IdModule = idModule;
            porControl.Name = name;
            porControl.Route = route;
            return porControl;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdControl
        {
            get
            {
                return _IdControl;
            }
            set
            {
                if (_IdControl != value)
                {
                    OnIdControlChanging(value);
                    ReportPropertyChanging("IdControl");
                    _IdControl = StructuralObject.SetValidValue(value, "IdControl");
                    ReportPropertyChanged("IdControl");
                    OnIdControlChanged();
                }
            }
        }
        private global::System.Int32 _IdControl;
        partial void OnIdControlChanging(global::System.Int32 value);
        partial void OnIdControlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdModule
        {
            get
            {
                return _IdModule;
            }
            set
            {
                OnIdModuleChanging(value);
                ReportPropertyChanging("IdModule");
                _IdModule = StructuralObject.SetValidValue(value, "IdModule");
                ReportPropertyChanged("IdModule");
                OnIdModuleChanged();
            }
        }
        private global::System.Int32 _IdModule;
        partial void OnIdModuleChanging(global::System.Int32 value);
        partial void OnIdModuleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Route
        {
            get
            {
                return _Route;
            }
            set
            {
                OnRouteChanging(value);
                ReportPropertyChanging("Route");
                _Route = StructuralObject.SetValidValue(value, false, "Route");
                ReportPropertyChanged("Route");
                OnRouteChanged();
            }
        }
        private global::System.String _Route;
        partial void OnRouteChanging(global::System.String value);
        partial void OnRouteChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PortalModel", Name="porFolder")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class porFolder : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new porFolder object.
        /// </summary>
        /// <param name="idFolder">Initial value of the IdFolder property.</param>
        /// <param name="idWebSite">Initial value of the IdWebSite property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static porFolder CreateporFolder(global::System.Int32 idFolder, global::System.Int32 idWebSite, global::System.String name)
        {
            porFolder porFolder = new porFolder();
            porFolder.IdFolder = idFolder;
            porFolder.IdWebSite = idWebSite;
            porFolder.Name = name;
            return porFolder;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdFolder
        {
            get
            {
                return _IdFolder;
            }
            set
            {
                if (_IdFolder != value)
                {
                    OnIdFolderChanging(value);
                    ReportPropertyChanging("IdFolder");
                    _IdFolder = StructuralObject.SetValidValue(value, "IdFolder");
                    ReportPropertyChanged("IdFolder");
                    OnIdFolderChanged();
                }
            }
        }
        private global::System.Int32 _IdFolder;
        partial void OnIdFolderChanging(global::System.Int32 value);
        partial void OnIdFolderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdWebSite
        {
            get
            {
                return _IdWebSite;
            }
            set
            {
                OnIdWebSiteChanging(value);
                ReportPropertyChanging("IdWebSite");
                _IdWebSite = StructuralObject.SetValidValue(value, "IdWebSite");
                ReportPropertyChanged("IdWebSite");
                OnIdWebSiteChanged();
            }
        }
        private global::System.Int32 _IdWebSite;
        partial void OnIdWebSiteChanging(global::System.Int32 value);
        partial void OnIdWebSiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdFolderParent
        {
            get
            {
                return _IdFolderParent;
            }
            set
            {
                OnIdFolderParentChanging(value);
                ReportPropertyChanging("IdFolderParent");
                _IdFolderParent = StructuralObject.SetValidValue(value, "IdFolderParent");
                ReportPropertyChanged("IdFolderParent");
                OnIdFolderParentChanged();
            }
        }
        private Nullable<global::System.Int32> _IdFolderParent;
        partial void OnIdFolderParentChanging(Nullable<global::System.Int32> value);
        partial void OnIdFolderParentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PortalModel", "FK_porFolder_IdFolderParent", "porFolder1")]
        public EntityCollection<porFolder> porFolder1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<porFolder>("PortalModel.FK_porFolder_IdFolderParent", "porFolder1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<porFolder>("PortalModel.FK_porFolder_IdFolderParent", "porFolder1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PortalModel", "FK_porFolder_IdFolderParent", "porFolder")]
        public porFolder porFolder2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<porFolder>("PortalModel.FK_porFolder_IdFolderParent", "porFolder").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<porFolder>("PortalModel.FK_porFolder_IdFolderParent", "porFolder").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<porFolder> porFolder2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<porFolder>("PortalModel.FK_porFolder_IdFolderParent", "porFolder");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<porFolder>("PortalModel.FK_porFolder_IdFolderParent", "porFolder", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PortalModel", "FK_porPage_IdFolder", "porPage")]
        public EntityCollection<porPage> porPages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<porPage>("PortalModel.FK_porPage_IdFolder", "porPage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<porPage>("PortalModel.FK_porPage_IdFolder", "porPage", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PortalModel", Name="porPage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class porPage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new porPage object.
        /// </summary>
        /// <param name="idPage">Initial value of the IdPage property.</param>
        /// <param name="idFolder">Initial value of the IdFolder property.</param>
        /// <param name="idWebSite">Initial value of the IdWebSite property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="url">Initial value of the Url property.</param>
        /// <param name="html">Initial value of the Html property.</param>
        public static porPage CreateporPage(global::System.Int32 idPage, global::System.Int32 idFolder, global::System.Int32 idWebSite, global::System.String name, global::System.String url, global::System.String html)
        {
            porPage porPage = new porPage();
            porPage.IdPage = idPage;
            porPage.IdFolder = idFolder;
            porPage.IdWebSite = idWebSite;
            porPage.Name = name;
            porPage.Url = url;
            porPage.Html = html;
            return porPage;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPage
        {
            get
            {
                return _IdPage;
            }
            set
            {
                if (_IdPage != value)
                {
                    OnIdPageChanging(value);
                    ReportPropertyChanging("IdPage");
                    _IdPage = StructuralObject.SetValidValue(value, "IdPage");
                    ReportPropertyChanged("IdPage");
                    OnIdPageChanged();
                }
            }
        }
        private global::System.Int32 _IdPage;
        partial void OnIdPageChanging(global::System.Int32 value);
        partial void OnIdPageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdTemplate
        {
            get
            {
                return _IdTemplate;
            }
            set
            {
                OnIdTemplateChanging(value);
                ReportPropertyChanging("IdTemplate");
                _IdTemplate = StructuralObject.SetValidValue(value, "IdTemplate");
                ReportPropertyChanged("IdTemplate");
                OnIdTemplateChanged();
            }
        }
        private Nullable<global::System.Int32> _IdTemplate;
        partial void OnIdTemplateChanging(Nullable<global::System.Int32> value);
        partial void OnIdTemplateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdFolder
        {
            get
            {
                return _IdFolder;
            }
            set
            {
                OnIdFolderChanging(value);
                ReportPropertyChanging("IdFolder");
                _IdFolder = StructuralObject.SetValidValue(value, "IdFolder");
                ReportPropertyChanged("IdFolder");
                OnIdFolderChanged();
            }
        }
        private global::System.Int32 _IdFolder;
        partial void OnIdFolderChanging(global::System.Int32 value);
        partial void OnIdFolderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdWebSite
        {
            get
            {
                return _IdWebSite;
            }
            set
            {
                OnIdWebSiteChanging(value);
                ReportPropertyChanging("IdWebSite");
                _IdWebSite = StructuralObject.SetValidValue(value, "IdWebSite");
                ReportPropertyChanged("IdWebSite");
                OnIdWebSiteChanged();
            }
        }
        private global::System.Int32 _IdWebSite;
        partial void OnIdWebSiteChanging(global::System.Int32 value);
        partial void OnIdWebSiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false, "Url");
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Html
        {
            get
            {
                return _Html;
            }
            set
            {
                OnHtmlChanging(value);
                ReportPropertyChanging("Html");
                _Html = StructuralObject.SetValidValue(value, false, "Html");
                ReportPropertyChanged("Html");
                OnHtmlChanged();
            }
        }
        private global::System.String _Html;
        partial void OnHtmlChanging(global::System.String value);
        partial void OnHtmlChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PortalModel", "FK_porPage_IdFolder", "porFolder")]
        public porFolder porFolder
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<porFolder>("PortalModel.FK_porPage_IdFolder", "porFolder").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<porFolder>("PortalModel.FK_porPage_IdFolder", "porFolder").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<porFolder> porFolderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<porFolder>("PortalModel.FK_porPage_IdFolder", "porFolder");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<porFolder>("PortalModel.FK_porPage_IdFolder", "porFolder", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PortalModel", "FK_porPage_IdTemplate", "porTemplate")]
        public porTemplate porTemplate
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<porTemplate>("PortalModel.FK_porPage_IdTemplate", "porTemplate").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<porTemplate>("PortalModel.FK_porPage_IdTemplate", "porTemplate").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<porTemplate> porTemplateReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<porTemplate>("PortalModel.FK_porPage_IdTemplate", "porTemplate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<porTemplate>("PortalModel.FK_porPage_IdTemplate", "porTemplate", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PortalModel", Name="porPagePartial")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class porPagePartial : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new porPagePartial object.
        /// </summary>
        /// <param name="idPagePartial">Initial value of the IdPagePartial property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="html">Initial value of the Html property.</param>
        public static porPagePartial CreateporPagePartial(global::System.Int32 idPagePartial, global::System.String name, global::System.String html)
        {
            porPagePartial porPagePartial = new porPagePartial();
            porPagePartial.IdPagePartial = idPagePartial;
            porPagePartial.Name = name;
            porPagePartial.Html = html;
            return porPagePartial;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPagePartial
        {
            get
            {
                return _IdPagePartial;
            }
            set
            {
                if (_IdPagePartial != value)
                {
                    OnIdPagePartialChanging(value);
                    ReportPropertyChanging("IdPagePartial");
                    _IdPagePartial = StructuralObject.SetValidValue(value, "IdPagePartial");
                    ReportPropertyChanged("IdPagePartial");
                    OnIdPagePartialChanged();
                }
            }
        }
        private global::System.Int32 _IdPagePartial;
        partial void OnIdPagePartialChanging(global::System.Int32 value);
        partial void OnIdPagePartialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Html
        {
            get
            {
                return _Html;
            }
            set
            {
                OnHtmlChanging(value);
                ReportPropertyChanging("Html");
                _Html = StructuralObject.SetValidValue(value, false, "Html");
                ReportPropertyChanged("Html");
                OnHtmlChanged();
            }
        }
        private global::System.String _Html;
        partial void OnHtmlChanging(global::System.String value);
        partial void OnHtmlChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PortalModel", Name="porTemplate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class porTemplate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new porTemplate object.
        /// </summary>
        /// <param name="idTemplate">Initial value of the IdTemplate property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="html">Initial value of the Html property.</param>
        public static porTemplate CreateporTemplate(global::System.Int32 idTemplate, global::System.String name, global::System.String html)
        {
            porTemplate porTemplate = new porTemplate();
            porTemplate.IdTemplate = idTemplate;
            porTemplate.Name = name;
            porTemplate.Html = html;
            return porTemplate;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdTemplate
        {
            get
            {
                return _IdTemplate;
            }
            set
            {
                if (_IdTemplate != value)
                {
                    OnIdTemplateChanging(value);
                    ReportPropertyChanging("IdTemplate");
                    _IdTemplate = StructuralObject.SetValidValue(value, "IdTemplate");
                    ReportPropertyChanged("IdTemplate");
                    OnIdTemplateChanged();
                }
            }
        }
        private global::System.Int32 _IdTemplate;
        partial void OnIdTemplateChanging(global::System.Int32 value);
        partial void OnIdTemplateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Html
        {
            get
            {
                return _Html;
            }
            set
            {
                OnHtmlChanging(value);
                ReportPropertyChanging("Html");
                _Html = StructuralObject.SetValidValue(value, false, "Html");
                ReportPropertyChanged("Html");
                OnHtmlChanged();
            }
        }
        private global::System.String _Html;
        partial void OnHtmlChanging(global::System.String value);
        partial void OnHtmlChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PortalModel", "FK_porPage_IdTemplate", "porPage")]
        public EntityCollection<porPage> porPages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<porPage>("PortalModel.FK_porPage_IdTemplate", "porPage");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<porPage>("PortalModel.FK_porPage_IdTemplate", "porPage", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PortalModel", Name="porUrlMapping")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class porUrlMapping : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new porUrlMapping object.
        /// </summary>
        /// <param name="idWebSite">Initial value of the IdWebSite property.</param>
        /// <param name="urlFrom">Initial value of the UrlFrom property.</param>
        /// <param name="urlTo">Initial value of the UrlTo property.</param>
        public static porUrlMapping CreateporUrlMapping(global::System.Int32 idWebSite, global::System.String urlFrom, global::System.String urlTo)
        {
            porUrlMapping porUrlMapping = new porUrlMapping();
            porUrlMapping.IdWebSite = idWebSite;
            porUrlMapping.UrlFrom = urlFrom;
            porUrlMapping.UrlTo = urlTo;
            return porUrlMapping;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdWebSite
        {
            get
            {
                return _IdWebSite;
            }
            set
            {
                if (_IdWebSite != value)
                {
                    OnIdWebSiteChanging(value);
                    ReportPropertyChanging("IdWebSite");
                    _IdWebSite = StructuralObject.SetValidValue(value, "IdWebSite");
                    ReportPropertyChanged("IdWebSite");
                    OnIdWebSiteChanged();
                }
            }
        }
        private global::System.Int32 _IdWebSite;
        partial void OnIdWebSiteChanging(global::System.Int32 value);
        partial void OnIdWebSiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UrlFrom
        {
            get
            {
                return _UrlFrom;
            }
            set
            {
                if (_UrlFrom != value)
                {
                    OnUrlFromChanging(value);
                    ReportPropertyChanging("UrlFrom");
                    _UrlFrom = StructuralObject.SetValidValue(value, false, "UrlFrom");
                    ReportPropertyChanged("UrlFrom");
                    OnUrlFromChanged();
                }
            }
        }
        private global::System.String _UrlFrom;
        partial void OnUrlFromChanging(global::System.String value);
        partial void OnUrlFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UrlTo
        {
            get
            {
                return _UrlTo;
            }
            set
            {
                OnUrlToChanging(value);
                ReportPropertyChanging("UrlTo");
                _UrlTo = StructuralObject.SetValidValue(value, false, "UrlTo");
                ReportPropertyChanged("UrlTo");
                OnUrlToChanged();
            }
        }
        private global::System.String _UrlTo;
        partial void OnUrlToChanging(global::System.String value);
        partial void OnUrlToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DtFrom
        {
            get
            {
                return _DtFrom;
            }
            set
            {
                OnDtFromChanging(value);
                ReportPropertyChanging("DtFrom");
                _DtFrom = StructuralObject.SetValidValue(value, "DtFrom");
                ReportPropertyChanged("DtFrom");
                OnDtFromChanged();
            }
        }
        private Nullable<global::System.DateTime> _DtFrom;
        partial void OnDtFromChanging(Nullable<global::System.DateTime> value);
        partial void OnDtFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DtTo
        {
            get
            {
                return _DtTo;
            }
            set
            {
                OnDtToChanging(value);
                ReportPropertyChanging("DtTo");
                _DtTo = StructuralObject.SetValidValue(value, "DtTo");
                ReportPropertyChanged("DtTo");
                OnDtToChanged();
            }
        }
        private Nullable<global::System.DateTime> _DtTo;
        partial void OnDtToChanging(Nullable<global::System.DateTime> value);
        partial void OnDtToChanged();

        #endregion

    }

    #endregion

}
