//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Account
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AccountEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AccountEntities object using the connection string found in the 'AccountEntities' section of the application configuration file.
        /// </summary>
        public AccountEntities() : base("name=AccountEntities", "AccountEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AccountEntities object.
        /// </summary>
        public AccountEntities(string connectionString) : base(connectionString, "AccountEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AccountEntities object.
        /// </summary>
        public AccountEntities(EntityConnection connection) : base(connection, "AccountEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<accAdministrator> accAdministrators
        {
            get
            {
                if ((_accAdministrators == null))
                {
                    _accAdministrators = base.CreateObjectSet<accAdministrator>("accAdministrators");
                }
                return _accAdministrators;
            }
        }
        private ObjectSet<accAdministrator> _accAdministrators;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<accModule> accModules
        {
            get
            {
                if ((_accModules == null))
                {
                    _accModules = base.CreateObjectSet<accModule>("accModules");
                }
                return _accModules;
            }
        }
        private ObjectSet<accModule> _accModules;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<accPermission> accPermissions
        {
            get
            {
                if ((_accPermissions == null))
                {
                    _accPermissions = base.CreateObjectSet<accPermission>("accPermissions");
                }
                return _accPermissions;
            }
        }
        private ObjectSet<accPermission> _accPermissions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<accProfile> accProfiles
        {
            get
            {
                if ((_accProfiles == null))
                {
                    _accProfiles = base.CreateObjectSet<accProfile>("accProfiles");
                }
                return _accProfiles;
            }
        }
        private ObjectSet<accProfile> _accProfiles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<accProfilePermission> accProfilePermissions
        {
            get
            {
                if ((_accProfilePermissions == null))
                {
                    _accProfilePermissions = base.CreateObjectSet<accProfilePermission>("accProfilePermissions");
                }
                return _accProfilePermissions;
            }
        }
        private ObjectSet<accProfilePermission> _accProfilePermissions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<accWebSiteConfig> accWebSiteConfigs
        {
            get
            {
                if ((_accWebSiteConfigs == null))
                {
                    _accWebSiteConfigs = base.CreateObjectSet<accWebSiteConfig>("accWebSiteConfigs");
                }
                return _accWebSiteConfigs;
            }
        }
        private ObjectSet<accWebSiteConfig> _accWebSiteConfigs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<accWebSiteModule> accWebSiteModules
        {
            get
            {
                if ((_accWebSiteModules == null))
                {
                    _accWebSiteModules = base.CreateObjectSet<accWebSiteModule>("accWebSiteModules");
                }
                return _accWebSiteModules;
            }
        }
        private ObjectSet<accWebSiteModule> _accWebSiteModules;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<accWebSite> accWebSites
        {
            get
            {
                if ((_accWebSites == null))
                {
                    _accWebSites = base.CreateObjectSet<accWebSite>("accWebSites");
                }
                return _accWebSites;
            }
        }
        private ObjectSet<accWebSite> _accWebSites;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the accAdministrators EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaccAdministrators(accAdministrator accAdministrator)
        {
            base.AddObject("accAdministrators", accAdministrator);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the accModules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaccModules(accModule accModule)
        {
            base.AddObject("accModules", accModule);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the accPermissions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaccPermissions(accPermission accPermission)
        {
            base.AddObject("accPermissions", accPermission);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the accProfiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaccProfiles(accProfile accProfile)
        {
            base.AddObject("accProfiles", accProfile);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the accProfilePermissions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaccProfilePermissions(accProfilePermission accProfilePermission)
        {
            base.AddObject("accProfilePermissions", accProfilePermission);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the accWebSiteConfigs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaccWebSiteConfigs(accWebSiteConfig accWebSiteConfig)
        {
            base.AddObject("accWebSiteConfigs", accWebSiteConfig);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the accWebSiteModules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaccWebSiteModules(accWebSiteModule accWebSiteModule)
        {
            base.AddObject("accWebSiteModules", accWebSiteModule);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the accWebSites EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaccWebSites(accWebSite accWebSite)
        {
            base.AddObject("accWebSites", accWebSite);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AccountModel", Name="accAdministrator")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class accAdministrator : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new accAdministrator object.
        /// </summary>
        /// <param name="idPerson">Initial value of the IdPerson property.</param>
        /// <param name="idProfile">Initial value of the IdProfile property.</param>
        /// <param name="codeName">Initial value of the CodeName property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="login">Initial value of the Login property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static accAdministrator CreateaccAdministrator(global::System.Int32 idPerson, global::System.Int32 idProfile, global::System.String codeName, global::System.String email, global::System.String login, global::System.String password)
        {
            accAdministrator accAdministrator = new accAdministrator();
            accAdministrator.IdPerson = idPerson;
            accAdministrator.IdProfile = idProfile;
            accAdministrator.CodeName = codeName;
            accAdministrator.Email = email;
            accAdministrator.Login = login;
            accAdministrator.Password = password;
            return accAdministrator;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPerson
        {
            get
            {
                return _IdPerson;
            }
            set
            {
                if (_IdPerson != value)
                {
                    OnIdPersonChanging(value);
                    ReportPropertyChanging("IdPerson");
                    _IdPerson = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdPerson");
                    OnIdPersonChanged();
                }
            }
        }
        private global::System.Int32 _IdPerson;
        partial void OnIdPersonChanging(global::System.Int32 value);
        partial void OnIdPersonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdProfile
        {
            get
            {
                return _IdProfile;
            }
            set
            {
                OnIdProfileChanging(value);
                ReportPropertyChanging("IdProfile");
                _IdProfile = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdProfile");
                OnIdProfileChanged();
            }
        }
        private global::System.Int32 _IdProfile;
        partial void OnIdProfileChanging(global::System.Int32 value);
        partial void OnIdProfileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CodeName
        {
            get
            {
                return _CodeName;
            }
            set
            {
                OnCodeNameChanging(value);
                ReportPropertyChanging("CodeName");
                _CodeName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CodeName");
                OnCodeNameChanged();
            }
        }
        private global::System.String _CodeName;
        partial void OnCodeNameChanging(global::System.String value);
        partial void OnCodeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Login
        {
            get
            {
                return _Login;
            }
            set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private global::System.String _Login;
        partial void OnLoginChanging(global::System.String value);
        partial void OnLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AccountModel", Name="accModule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class accModule : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new accModule object.
        /// </summary>
        /// <param name="idModule">Initial value of the IdModule property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static accModule CreateaccModule(global::System.Int32 idModule, global::System.String name)
        {
            accModule accModule = new accModule();
            accModule.IdModule = idModule;
            accModule.Name = name;
            return accModule;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdModule
        {
            get
            {
                return _IdModule;
            }
            set
            {
                if (_IdModule != value)
                {
                    OnIdModuleChanging(value);
                    ReportPropertyChanging("IdModule");
                    _IdModule = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdModule");
                    OnIdModuleChanged();
                }
            }
        }
        private global::System.Int32 _IdModule;
        partial void OnIdModuleChanging(global::System.Int32 value);
        partial void OnIdModuleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AccountModel", Name="accPermission")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class accPermission : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new accPermission object.
        /// </summary>
        /// <param name="idPermission">Initial value of the IdPermission property.</param>
        /// <param name="idModule">Initial value of the IdModule property.</param>
        public static accPermission CreateaccPermission(global::System.Int32 idPermission, global::System.Int32 idModule)
        {
            accPermission accPermission = new accPermission();
            accPermission.IdPermission = idPermission;
            accPermission.IdModule = idModule;
            return accPermission;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPermission
        {
            get
            {
                return _IdPermission;
            }
            set
            {
                if (_IdPermission != value)
                {
                    OnIdPermissionChanging(value);
                    ReportPropertyChanging("IdPermission");
                    _IdPermission = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdPermission");
                    OnIdPermissionChanged();
                }
            }
        }
        private global::System.Int32 _IdPermission;
        partial void OnIdPermissionChanging(global::System.Int32 value);
        partial void OnIdPermissionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdModule
        {
            get
            {
                return _IdModule;
            }
            set
            {
                OnIdModuleChanging(value);
                ReportPropertyChanging("IdModule");
                _IdModule = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdModule");
                OnIdModuleChanged();
            }
        }
        private global::System.Int32 _IdModule;
        partial void OnIdModuleChanging(global::System.Int32 value);
        partial void OnIdModuleChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AccountModel", Name="accProfile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class accProfile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new accProfile object.
        /// </summary>
        /// <param name="idProfile">Initial value of the IdProfile property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static accProfile CreateaccProfile(global::System.Int32 idProfile, global::System.String name)
        {
            accProfile accProfile = new accProfile();
            accProfile.IdProfile = idProfile;
            accProfile.Name = name;
            return accProfile;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdProfile
        {
            get
            {
                return _IdProfile;
            }
            set
            {
                if (_IdProfile != value)
                {
                    OnIdProfileChanging(value);
                    ReportPropertyChanging("IdProfile");
                    _IdProfile = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdProfile");
                    OnIdProfileChanged();
                }
            }
        }
        private global::System.Int32 _IdProfile;
        partial void OnIdProfileChanging(global::System.Int32 value);
        partial void OnIdProfileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AccountModel", Name="accProfilePermission")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class accProfilePermission : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new accProfilePermission object.
        /// </summary>
        /// <param name="idProfile">Initial value of the IdProfile property.</param>
        /// <param name="idPermission">Initial value of the IdPermission property.</param>
        /// <param name="create">Initial value of the Create property.</param>
        /// <param name="read">Initial value of the Read property.</param>
        /// <param name="update">Initial value of the Update property.</param>
        /// <param name="delete">Initial value of the Delete property.</param>
        public static accProfilePermission CreateaccProfilePermission(global::System.Int32 idProfile, global::System.Int32 idPermission, global::System.Boolean create, global::System.Boolean read, global::System.Boolean update, global::System.Boolean delete)
        {
            accProfilePermission accProfilePermission = new accProfilePermission();
            accProfilePermission.IdProfile = idProfile;
            accProfilePermission.IdPermission = idPermission;
            accProfilePermission.Create = create;
            accProfilePermission.Read = read;
            accProfilePermission.Update = update;
            accProfilePermission.Delete = delete;
            return accProfilePermission;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdProfile
        {
            get
            {
                return _IdProfile;
            }
            set
            {
                if (_IdProfile != value)
                {
                    OnIdProfileChanging(value);
                    ReportPropertyChanging("IdProfile");
                    _IdProfile = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdProfile");
                    OnIdProfileChanged();
                }
            }
        }
        private global::System.Int32 _IdProfile;
        partial void OnIdProfileChanging(global::System.Int32 value);
        partial void OnIdProfileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPermission
        {
            get
            {
                return _IdPermission;
            }
            set
            {
                if (_IdPermission != value)
                {
                    OnIdPermissionChanging(value);
                    ReportPropertyChanging("IdPermission");
                    _IdPermission = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdPermission");
                    OnIdPermissionChanged();
                }
            }
        }
        private global::System.Int32 _IdPermission;
        partial void OnIdPermissionChanging(global::System.Int32 value);
        partial void OnIdPermissionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Create
        {
            get
            {
                return _Create;
            }
            set
            {
                OnCreateChanging(value);
                ReportPropertyChanging("Create");
                _Create = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Create");
                OnCreateChanged();
            }
        }
        private global::System.Boolean _Create;
        partial void OnCreateChanging(global::System.Boolean value);
        partial void OnCreateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Read
        {
            get
            {
                return _Read;
            }
            set
            {
                OnReadChanging(value);
                ReportPropertyChanging("Read");
                _Read = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Read");
                OnReadChanged();
            }
        }
        private global::System.Boolean _Read;
        partial void OnReadChanging(global::System.Boolean value);
        partial void OnReadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Update
        {
            get
            {
                return _Update;
            }
            set
            {
                OnUpdateChanging(value);
                ReportPropertyChanging("Update");
                _Update = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Update");
                OnUpdateChanged();
            }
        }
        private global::System.Boolean _Update;
        partial void OnUpdateChanging(global::System.Boolean value);
        partial void OnUpdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Delete
        {
            get
            {
                return _Delete;
            }
            set
            {
                OnDeleteChanging(value);
                ReportPropertyChanging("Delete");
                _Delete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Delete");
                OnDeleteChanged();
            }
        }
        private global::System.Boolean _Delete;
        partial void OnDeleteChanging(global::System.Boolean value);
        partial void OnDeleteChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AccountModel", Name="accWebSite")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class accWebSite : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new accWebSite object.
        /// </summary>
        /// <param name="idWebSite">Initial value of the IdWebSite property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="isMaintenance">Initial value of the IsMaintenance property.</param>
        /// <param name="domain">Initial value of the Domain property.</param>
        /// <param name="domainGipo">Initial value of the DomainGipo property.</param>
        public static accWebSite CreateaccWebSite(global::System.Int32 idWebSite, global::System.String name, global::System.Boolean isMaintenance, global::System.String domain, global::System.String domainGipo)
        {
            accWebSite accWebSite = new accWebSite();
            accWebSite.IdWebSite = idWebSite;
            accWebSite.Name = name;
            accWebSite.IsMaintenance = isMaintenance;
            accWebSite.Domain = domain;
            accWebSite.DomainGipo = domainGipo;
            return accWebSite;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdWebSite
        {
            get
            {
                return _IdWebSite;
            }
            set
            {
                if (_IdWebSite != value)
                {
                    OnIdWebSiteChanging(value);
                    ReportPropertyChanging("IdWebSite");
                    _IdWebSite = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdWebSite");
                    OnIdWebSiteChanged();
                }
            }
        }
        private global::System.Int32 _IdWebSite;
        partial void OnIdWebSiteChanging(global::System.Int32 value);
        partial void OnIdWebSiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsMaintenance
        {
            get
            {
                return _IsMaintenance;
            }
            set
            {
                OnIsMaintenanceChanging(value);
                ReportPropertyChanging("IsMaintenance");
                _IsMaintenance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsMaintenance");
                OnIsMaintenanceChanged();
            }
        }
        private global::System.Boolean _IsMaintenance;
        partial void OnIsMaintenanceChanging(global::System.Boolean value);
        partial void OnIsMaintenanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Domain
        {
            get
            {
                return _Domain;
            }
            set
            {
                OnDomainChanging(value);
                ReportPropertyChanging("Domain");
                _Domain = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Domain");
                OnDomainChanged();
            }
        }
        private global::System.String _Domain;
        partial void OnDomainChanging(global::System.String value);
        partial void OnDomainChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DomainGipo
        {
            get
            {
                return _DomainGipo;
            }
            set
            {
                OnDomainGipoChanging(value);
                ReportPropertyChanging("DomainGipo");
                _DomainGipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DomainGipo");
                OnDomainGipoChanged();
            }
        }
        private global::System.String _DomainGipo;
        partial void OnDomainGipoChanging(global::System.String value);
        partial void OnDomainGipoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AccountModel", Name="accWebSiteConfig")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class accWebSiteConfig : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new accWebSiteConfig object.
        /// </summary>
        /// <param name="idWebSite">Initial value of the IdWebSite property.</param>
        public static accWebSiteConfig CreateaccWebSiteConfig(global::System.Int32 idWebSite)
        {
            accWebSiteConfig accWebSiteConfig = new accWebSiteConfig();
            accWebSiteConfig.IdWebSite = idWebSite;
            return accWebSiteConfig;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdWebSite
        {
            get
            {
                return _IdWebSite;
            }
            set
            {
                if (_IdWebSite != value)
                {
                    OnIdWebSiteChanging(value);
                    ReportPropertyChanging("IdWebSite");
                    _IdWebSite = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdWebSite");
                    OnIdWebSiteChanged();
                }
            }
        }
        private global::System.Int32 _IdWebSite;
        partial void OnIdWebSiteChanging(global::System.Int32 value);
        partial void OnIdWebSiteChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AccountModel", Name="accWebSiteModule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class accWebSiteModule : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new accWebSiteModule object.
        /// </summary>
        /// <param name="idWebSite">Initial value of the IdWebSite property.</param>
        /// <param name="idModule">Initial value of the IdModule property.</param>
        public static accWebSiteModule CreateaccWebSiteModule(global::System.Int32 idWebSite, global::System.Int32 idModule)
        {
            accWebSiteModule accWebSiteModule = new accWebSiteModule();
            accWebSiteModule.IdWebSite = idWebSite;
            accWebSiteModule.IdModule = idModule;
            return accWebSiteModule;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdWebSite
        {
            get
            {
                return _IdWebSite;
            }
            set
            {
                if (_IdWebSite != value)
                {
                    OnIdWebSiteChanging(value);
                    ReportPropertyChanging("IdWebSite");
                    _IdWebSite = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdWebSite");
                    OnIdWebSiteChanged();
                }
            }
        }
        private global::System.Int32 _IdWebSite;
        partial void OnIdWebSiteChanging(global::System.Int32 value);
        partial void OnIdWebSiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdModule
        {
            get
            {
                return _IdModule;
            }
            set
            {
                if (_IdModule != value)
                {
                    OnIdModuleChanging(value);
                    ReportPropertyChanging("IdModule");
                    _IdModule = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdModule");
                    OnIdModuleChanged();
                }
            }
        }
        private global::System.Int32 _IdModule;
        partial void OnIdModuleChanging(global::System.Int32 value);
        partial void OnIdModuleChanged();

        #endregion
    
    }

    #endregion
    
}
