//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Connection
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ConnectionEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ConnectionEntities object using the connection string found in the 'ConnectionEntities' section of the application configuration file.
        /// </summary>
        public ConnectionEntities() : base("name=ConnectionEntities", "ConnectionEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ConnectionEntities object.
        /// </summary>
        public ConnectionEntities(string connectionString) : base(connectionString, "ConnectionEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ConnectionEntities object.
        /// </summary>
        public ConnectionEntities(EntityConnection connection) : base(connection, "ConnectionEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<conConnection> conConnections
        {
            get
            {
                if ((_conConnections == null))
                {
                    _conConnections = base.CreateObjectSet<conConnection>("conConnections");
                }
                return _conConnections;
            }
        }
        private ObjectSet<conConnection> _conConnections;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the conConnections EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToconConnections(conConnection conConnection)
        {
            base.AddObject("conConnections", conConnection);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ConnectionModel", Name="conConnection")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class conConnection : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new conConnection object.
        /// </summary>
        /// <param name="idConnection">Initial value of the IdConnection property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="connectionString">Initial value of the ConnectionString property.</param>
        /// <param name="domain">Initial value of the Domain property.</param>
        /// <param name="domainGipo">Initial value of the DomainGipo property.</param>
        public static conConnection CreateconConnection(global::System.Int32 idConnection, global::System.String name, global::System.String connectionString, global::System.String domain, global::System.String domainGipo)
        {
            conConnection conConnection = new conConnection();
            conConnection.IdConnection = idConnection;
            conConnection.Name = name;
            conConnection.ConnectionString = connectionString;
            conConnection.Domain = domain;
            conConnection.DomainGipo = domainGipo;
            return conConnection;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdConnection
        {
            get
            {
                return _IdConnection;
            }
            set
            {
                if (_IdConnection != value)
                {
                    OnIdConnectionChanging(value);
                    ReportPropertyChanging("IdConnection");
                    _IdConnection = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdConnection");
                    OnIdConnectionChanged();
                }
            }
        }
        private global::System.Int32 _IdConnection;
        partial void OnIdConnectionChanging(global::System.Int32 value);
        partial void OnIdConnectionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ConnectionString
        {
            get
            {
                return _ConnectionString;
            }
            set
            {
                OnConnectionStringChanging(value);
                ReportPropertyChanging("ConnectionString");
                _ConnectionString = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ConnectionString");
                OnConnectionStringChanged();
            }
        }
        private global::System.String _ConnectionString;
        partial void OnConnectionStringChanging(global::System.String value);
        partial void OnConnectionStringChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Domain
        {
            get
            {
                return _Domain;
            }
            set
            {
                OnDomainChanging(value);
                ReportPropertyChanging("Domain");
                _Domain = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Domain");
                OnDomainChanged();
            }
        }
        private global::System.String _Domain;
        partial void OnDomainChanging(global::System.String value);
        partial void OnDomainChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DomainGipo
        {
            get
            {
                return _DomainGipo;
            }
            set
            {
                OnDomainGipoChanging(value);
                ReportPropertyChanging("DomainGipo");
                _DomainGipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DomainGipo");
                OnDomainGipoChanged();
            }
        }
        private global::System.String _DomainGipo;
        partial void OnDomainGipoChanging(global::System.String value);
        partial void OnDomainGipoChanged();

        #endregion
    
    }

    #endregion
    
}
